name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        # See https://github.com/actions/python-versions/releases for available versions
        python-version: [ "3.10", "3.11", "3.12", "3.13.0-rc.2" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with Mypy
        run: |
          poetry run mypy trengo

      - name: Run Tests
        run: |
          poetry run pytest -v

      - name: Test build
        run: |
          poetry build
